replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: "v0.9.0"

iam_role: ""  # e.g. "arn:aws:iam::012345678901:role/role-name"

adapter:
  args:
    cert-dir: /tmp
    secure-port: 6443
    logtostderr: true
    v: 2
