apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: externalmetrics.metrics.aws
  labels:
    {{- include "k8s-cloudwatch-adapter-crd.labels" . | nindent 4 }}
spec:
  group: metrics.aws
  version: v1alpha1
  names:
    kind: ExternalMetric
    plural: externalmetrics
    singular: externalmetric
    shortNames:
      - em
  scope: Namespaced
