apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-cloudwatch-adapter-crd.fullname" . }}:crd-metrics-reader
  labels:
    {{- include "k8s-cloudwatch-adapter-crd.labels" . | nindent 4 }}
rules:
- apiGroups:
  - metrics.aws
  resources:
  - "externalmetrics"
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-cloudwatch-adapter-crd.fullname" . }}:crd-metrics-reader
  labels:
    {{- include "k8s-cloudwatch-adapter-crd.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-cloudwatch-adapter-crd.fullname" . }}:crd-metrics-reader
subjects:
  - name: {{ template "k8s-cloudwatch-adapter-crd.serviceAccountName" . }}
    kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
