apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-cloudwatch-adapter.labels" . | nindent 4 }}
spec:
  service:
    name: {{ include "k8s-cloudwatch-adapter.fullname" . }}
    namespace: {{ .Release.Namespace }}
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
