apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: externalmetrics.metrics.aws
  labels:
    {{- include "k8s-cloudwatch-adapter.labels" . | nindent 4 }}
spec:
  group: metrics.aws
  version: v1alpha1
  names:
    kind: ExternalMetric
    plural: externalmetrics
    singular: externalmetric
  scope: Namespaced
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-cloudwatch-adapter.fullname" . }}:crd-metrics-reader
  labels:
    {{- include "k8s-cloudwatch-adapter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - metrics.aws
  resources:
  - "externalmetrics"
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-cloudwatch-adapter.fullname" . }}:crd-metrics-reader
  labels:
    {{- include "k8s-cloudwatch-adapter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-cloudwatch-adapter.fullname" . }}:crd-metrics-reader
subjects:
  - name: {{ template "k8s-cloudwatch-adapter.serviceAccountName" . }}
    kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
