apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "k8s-cloudwatch-adapter.labels" . | nindent 4 }}
  name: {{ include "k8s-cloudwatch-adapter.fullname" . }}:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ template "k8s-cloudwatch-adapter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "k8s-cloudwatch-adapter.labels" . | nindent 4 }}
  name: {{ include "k8s-cloudwatch-adapter.fullname" . }}-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ template "k8s-cloudwatch-adapter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "k8s-cloudwatch-adapter.labels" . | nindent 4 }}
  name: {{ include "k8s-cloudwatch-adapter.fullname" . }}-resource-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-cloudwatch-adapter.fullname" . }}-resource-reader
subjects:
- kind: ServiceAccount
  name: {{ template "k8s-cloudwatch-adapter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "k8s-cloudwatch-adapter.labels" . | nindent 4 }}
  name: {{ include "k8s-cloudwatch-adapter.fullname" . }}:external-metrics-reader
rules:
- apiGroups:
  - external.metrics.k8s.io
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "k8s-cloudwatch-adapter.labels" . | nindent 4 }}
  name: {{ include "k8s-cloudwatch-adapter.fullname" . }}-resource-reader
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - configmaps
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "k8s-cloudwatch-adapter.labels" . | nindent 4 }}
  name: {{ include "k8s-cloudwatch-adapter.fullname" . }}:external-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-cloudwatch-adapter.fullname" . }}:external-metrics-reader
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
