apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations: {{ toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "k8s-cloudwatch-adapter.labels" . | nindent 4 }}
  {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
  {{- end }}
  name: {{ include "k8s-cloudwatch-adapter.fullname" . }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  - name: http
    port: 80
    targetPort: 8080
  selector:
    {{- include "k8s-cloudwatch-adapter.selectorLabels" . | nindent 4 }}
