{{- if .Values.serviceAccount.create -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    {{- include "k8s-cloudwatch-adapter.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.irsaIamRole }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.irsaIamRole }}
    {{- end }}
  name: {{ template "k8s-cloudwatch-adapter.serviceAccountName" . }}
{{- end }}
